# Generated by Django 3.2.23 on 2024-05-11 18:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('market_hash_name', models.CharField(max_length=256)),
                ('class_name', models.CharField(max_length=256, verbose_name='class')),
                ('instance', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('event', models.CharField(choices=[('Buy', 'buy'), ('Sell', 'sell')], max_length=256)),
                ('app', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=256)),
                ('for_who', models.CharField(blank=True, max_length=256, null=True, verbose_name='for')),
                ('amount', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True)),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Dota2ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='images/')),
                ('item_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='app.dota2item')),
            ],
        ),
    ]
