# Generated by Django 3.2.23 on 2024-04-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dota2Item',
            fields=[
                ('item_id', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('market_hash_name', models.CharField(max_length=256)),
                ('class_name', models.CharField(max_length=256)),
                ('instance', models.CharField(max_length=256)),
                ('time', models.CharField(max_length=256)),
                ('event', models.CharField(choices=[('Buy', 'buy'), ('Sell', 'sell')], max_length=256)),
                ('app', models.PositiveIntegerField()),
                ('stage', models.CharField(max_length=256)),
                ('for_who', models.CharField(blank=True, max_length=256, null=True)),
                ('custom_id', models.CharField(blank=True, max_length=256, null=True)),
                ('received', models.CharField(max_length=256)),
                ('paid', models.CharField(max_length=256)),
                ('currency', models.CharField(choices=[('RUB', 'RUB')], max_length=256)),
            ],
        ),
    ]
