# Generated by Django 3.2.23 on 2024-06-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dota2item',
            name='event',
            field=models.CharField(choices=[('buy', 'buy'), ('sell', 'sell')], max_length=256),
        ),
    ]
