# Generated by Django 3.2.23 on 2024-04-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20240427_1119'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dota2item',
            old_name='amount',
            new_name='paid',
        ),
        migrations.AddField(
            model_name='dota2item',
            name='received',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
