# Generated by Django 3.2.23 on 2024-04-27 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20240427_1143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dota2item',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='dota2item',
            name='received',
        ),
        migrations.AddField(
            model_name='dota2item',
            name='amount',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
